server:
  port: 8085

spring:
  application:
    name: gateway

  config:
    import: optional:configserver:http://localhost:8090
    #eğer config server a ihtiyacı olursa bu adresten bağlanıp baglanip kendi konsigurasyonunu buradan almasini sagliyorum
